### PR TITLE
feat(gmail): add purelymail

### PR DESCRIPTION
**Pull request by hashier**
Copy from their homepage:

Cheap, no-nonsense email
    We host your email address.
    We're IMAP and POP3 compatible, so we work with most mail apps.
    Or you can use our webmail, powered by Roundcube.
    No arbitrary limits. Have as many users and store as much mail as you want.
    Bring your own domain, or use one of ours. No extra charges.
    It's cheap. Really, really cheap.

### CODE REVIEW

**Comment by danarel** [comment]
https://www.hardenize.com/report/purelymail.com/1589174518

Doesn't hold up well on Hardenize. No DNSSEC, no TLS, no MTA-STS, no TLS-RPT, no DANE.

I'll give them the benefit of the doubt since they say they are in beta, but they really need to make some security improvements.

**Comment by hashier** [comment]
No TLS? They most definitely have TLS.

For the others, which host can you @danarel recommend that ticks all those boxes? I'm looking right now to move to a new hoster.

**Comment by danarel** [comment]
Sorry you’re right, they have TLS, but with some issues:

https://www.hardenize.com/report/purelymail.com/1589174518#email_tls

Providers that do pass all the tests are:

ProtonMail
Tutanota
StartMail
Mailbox.org
Soverin

To name a few. Posteo does as well but they don’t support custom domains.

**Comment by hashier** [comment]
Thanksgiving instill look at throbbed you mentioned. ProtonMail is out for me since they don’t support standard imap (without a weird bridge).

**Comment by danarel** [comment]
> Thanksgiving instill look at throbbed you mentioned. ProtonMail is out for me since they don’t support standard imap (without a weird bridge).

Yeah. Personally I don't use IMAP and mainly use ProtonMail for my email, but I have used Mailbox.org and StartMail as well and both support IMAP. I liked Startmail's GUI a bit better, easier to use.

**Comment by hashier** [comment]
Thanks!

And sorry for more-typos-than-real-words because of auto correct in my last message.

**Comment by tycrek** [comment]
> 
> 
> https://www.hardenize.com/report/purelymail.com/1589174518
> 
> Doesn't hold up well on Hardenize. No DNSSEC, no TLS, no MTA-STS, no TLS-RPT, no DANE.
> 
> I'll give them the benefit of the doubt since they say they are in beta, but they really need to make some security improvements.

I'll close this for now, eventually if they decide to add these security features I will reconsider adding them.

**Pull request closed without merging**
