### PR TITLE
Update degoogle.yml

### PR DESCRIPTION
**Pull request by thelifeofjay**
* Adds information from Copperhead about CopperheadOS
* Fixed previous indentation errors

Thanks @tycrek

### CODE REVIEW

**Comment by tycrek** [comment]
My bad @thelifeofjay, been a busy few days and haven't been paying much attention.

- https://old.reddit.com/r/CopperheadOS/comments/8qdnn3/goodbye/
- https://old.reddit.com/r/CopperheadOS/

Stickied post on the subreddit says:

> The open source mobile privacy/security project formerly known as CopperheadOS has been renamed to GrapheneOS. Please unsubscribe from /r/CopperheadOS and subscribe to the /r/GrapheneOS subreddit instead. Copperhead was taken over and is a malicious company not associated with the original project.

Sorry for having you make so many changes, but could you remove Copperhead completely? I'm fine with removing the references to it in Graphene's description too since the project has been dead for about 2 years now

**Comment by thelifeofjay** [comment]
Hi @tycrek.

> Stickied post on the subreddit says:

The /r/CopperheadOS subreddit has been defaced with incorrect information for over 2.5 years. [It's not a valid piece of information regarding Copperhead.](https://copperhead.co/android/docs/faq/#whats-up-with-your-old-subreddit)

> Sorry for having you make so many changes, but could you remove Copperhead completely?

CopperheadOS matches the requirements on this list for being de-Googled as [outlined on our website](https://copperhead.co/android). Is there criteria we're not following?

> since the project has been dead for about 2 years now

This is completely untrue information spread by hostile parties who don't like companies or commercialisation. [CopperheadOS has been routinely updated since 2016](https://copperhead.co/android/docs/updates/).

Happy to discuss further.

**Comment by tycrek** [comment]
Oh wow, I did not know that! Perhaps we should open an Issue as well for discussion before merging. Thanks for sharing those other links

**Comment by thelifeofjay** [comment]
Created https://github.com/tycrek/degoogle/issues/253. Thanks for the review and guidance.

**Comment by thelifeofjay** [comment]
@tycrek ping!

**Review by tycrek — APPROVED** [review]
Approved.

**Pull request merged**
