### PR TITLE
Updated README.md (added postale.io email hosting service)

### PR DESCRIPTION
**Pull request by DoobleD**
Trsutpilot reviews: https://www.trustpilot.com/review/postale.io?languages=all

### CODE REVIEW

**Comment by FreddyMarsden** [comment]
This site has 5 third party trackers connecting to it. 4 of them are from Google. Seeing as Migadu (which is already listed) can do the same thing for free, there is no reason for this to be listed.

**Comment by DoobleD** [comment]
Thank you for your feedback Freddy!

May I ask what are those 5 third party trackers, appart from Analytics?

I think Migadu is great, but its [free plan](https://www.migadu.com/en/pricing.html) has different limits than postale.io's [free plan](https://postale.io/pricing). 

Namely, Migadu offers unlimited email addresses per domain but each one is limited to 10 outgoing emails per day, and has "Sent via Migadu" appended to each email. In the other hand, postale.io offers only 5 free email addresses per domain, but each one is limited to hundreds of outgoing emails per day, and no text is added. Thought this could be of interest to some users, depending on their needs. Both paid plans are pretty cheap.

In any case thanks for taking the time to look at it! :)

**Comment by tycrek** [comment]
Personally, I'm not satisfied with the [privacy policy](https://postale.io/privacy-policy), namely the Third Party section.

**Comment by FreddyMarsden** [comment]
@DoobleD I used uBlock Origin to find out, however here is a [link](https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fpostale.io) to show you (you might need to scroll down)

**Comment by tycrek** [comment]
Doesn't hold up to [Hardenize](https://www.hardenize.com/report/postale.io/1590342613) `STARTTLS`.

**Comment by DoobleD** [comment]
Thanks @tycrek and @FreddyMarsden for your feedback! :)

**Pull request closed without merging**
