### PR TITLE
Add Google Alerts

### PR DESCRIPTION
**Pull request by qbi**

### CODE REVIEW

**Comment by tycrek** [comment]
What exactly is Google Alerts? Is it a consumer focused service or more enterprise?

**Comment by duckunix** [comment]
Google Alerts is a service from Google, so kinda defeats the purpose of this project, IMO.

> Google Alerts is a content change detection and notification service, offered by the search engine company Google. The service sends emails to the user when it finds new results—such as web pages, newspaper articles, blogs, or scientific research—that match the user's search term. In 2003, Google launched Google alerts which were the result of Naga Kataru's efforts. His name is on the three patents for Google Alerts. [Wikipedia](https://en.wikipedia.org/wiki/Google_Alerts)

**Comment by arp242** [comment]
> Google Alerts is a service from Google, so kinda defeats the purpose of this project, IMO.

It's not listed as an alternative, but as a heading to file alternatives under :-)

https://f5bot.com/ is a limited alternative, btw

**Comment by arp242** [comment]
> What exactly is Google Alerts? Is it a consumer focused service or more enterprise?

It alerts you if a specific string is mentioned/found online. You can use it to get notified if someone mentions your name, product, website, etc.

**Comment by tycrek** [comment]
@arp242 F5Bot looks very interesting. I think it could be a valid replacement. Personally, I'm satisfied with the [privacy policy](https://f5bot.com/privacy) but others can take a look too and let me know of their opinions on it. @arp242 , would you be able to make a separate pull request adding it in, or submit a [new issue with the [NEW] tag](https://github.com/tycrek/degoogle/issues/new?assignees=&labels=&template=new-alternative.md&title=%5BNEW%5D+New+alternative)?

**Comment by tycrek** [comment]
@arp242 Sorry for the repeated pings. I'm going to merge @qbi's PR so that you can have a section to make your PR if you so choose to.

**Pull request merged**
