### PR TITLE
Update degoogle.yml

### PR DESCRIPTION
**Pull request by mceachen**
(It's not open source).

### CODE REVIEW

**Comment by tycrek** [comment]
The [self-hosted option is open-source](https://github.com/photostructure/photostructure-for-servers) and the beta for Desktop is currently sign-up only. Because of that it's not worth making this change at this time.

**Comment by mceachen** [comment]
@tycrek Hi there! I'm the author of PhotoStructure. 

It's not open source, and it's not going to be [at least for a while](https://photostructure.com/faq/why-photostructure/#if-photostructure-inc-goes-away-photostructure-wont). 

Also, the [license](https://github.com/photostructure/photostructure-for-servers/blob/main/LICENSE.md) very clearly says that it is commercial software that retains all copyright and distribution rights.

**Comment by tycrek** [comment]
Facepalm moment 🤦‍♂️ 

Thanks for reaching out @mceachen, I'll definitely get that fixed!

**Comment by tycrek** [comment]
> I'll definitely get that fixed!

Been in the Issues too much today, you already have it fixed in this PR haha

**Comment by mceachen** [comment]
Thanks for reopening. Want me to resolve the conflict?

**Comment by tycrek** [comment]
> 
> 
> Thanks for reopening. Want me to resolve the conflict?

Just fixed it, but thanks for offering

**Comment by mceachen** [comment]
Thanks for this whole effort, btw! 

(also: you should totally try out PhotoStructure! I'd be delighted to give you a license as a thank you for this list: I give free licenses to all developers/maintainers of the libraries that PhotoStructure uses.)

**Comment by tycrek** [comment]
That would be great, thank you!

> **What I had, before I started PhotoStructure**: a pile of hard drives and old backups and duplicates and some files that had succumbed to bit rot. A big, intractable mess.
> **What I wanted**: a deduplicated set of all my photos and videos, in one organized folder hierarchy.

This is the exact situation I'm in right now haha, I'd love to give it a try

**Comment by mceachen** [comment]
Excellent: just sent you an email with info to the address associated to your github account.

**Pull request merged**
