### PR TITLE
EteSync: add the contacts (was already in calendar and tasks)

### PR DESCRIPTION
**Pull request by tasn**
For some reason EteSync wasn't listed under contacts (I guess the category was added
after EteSync was already on the list).
EteSync is already under calendar and tasks, this commit adds EteSync under contacts too.

### CODE REVIEW

**Comment by tasn** [comment]
Updated. Sorry for not reading the contribution guide before opening a PR. :facepalm:

**Comment by tycrek** [comment]
> 
> 
> Updated. Sorry for not reading the contribution guide before opening a PR. 🤦

No worries. I also added the F-Droid package.

**Comment by tasn** [comment]
Oh thanks. I just copied the other EteSync entry so I guess that was missing the f-droid package too. Should I open a new PR for that?

**Comment by tycrek** [comment]
Shouldn't be necessary; the F-Droid packages are mainly meant for the Mobile Apps category.

**Comment by tasn** [comment]
OK, thanks!

**Pull request merged**
